package(default_visibility = ["//visibility:public"])

cc_library(
    name = "config",
    srcs = [
        "config.cpp",
    ],
    hdrs = [
        "config.h",
    ],
    deps = [
        "//app:files",
        "//debug:log",
        "//pimpl",
        "//third_party/nlohmann:json",
    ],
)
