package(default_visibility = ["//visibility:public"])

cc_library(
    name = "linear_congruential_generator",
    srcs = ["linear_congruential_generator.cpp"],
    hdrs = ["linear_congruential_generator.h"],
    deps = [
        "//debug:check",
        "//seq",
    ],
)
