#!/usr/bin/env python3
import argparse
import sys
import pathlib


DELIM = r"~#.+^%&*=_]!-?["
CLOSING_SEQ = f"){DELIM}\""


def parse_args():
    parser = argparse.ArgumentParser(
        description="Embed multiple files into a single header."
    )

    parser.add_argument(
        "--readable",
        action="store_true",
        help=f"Embed as C++ raw string literals R\"{DELIM}(...){DELIM}\""
    )

    parser.add_argument(
        "output_h",
        help="Output .h file"
    )

    parser.add_argument(
        "rest",
        nargs=argparse.REMAINDER,
        help="symbol1 file1 symbol2 file2 ..."
    )

    args = parser.parse_args()

    rest = args.rest
    if len(rest) % 2 != 0 or len(rest) == 0:
        print("Error: Must supply pairs: <symbol1> <file1> [<symbol2> <file2> ...]",
              file=sys.stderr)
        sys.exit(1)

    pairs = []
    for i in range(0, len(rest), 2):
        sym = rest[i]
        f = pathlib.Path(rest[i + 1])
        pairs.append((sym, f))

    return args.output_h, args.readable, pairs


def emit_readable(h, symbol, path):
    data = path.read_bytes()

    # Validate UTF-8 text
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        print(f"embed_files.py: file {path} is not UTF-8; cannot use --readable",
              file=sys.stderr)
        sys.exit(1)

    if "\0" in text:
        print(f"embed_files.py: file {path} contains NUL; unsafe for raw-string",
              file=sys.stderr)
        sys.exit(1)

    if CLOSING_SEQ in text:
        print(
            f"embed_files.py: file {path} contains the forbidden sequence '{CLOSING_SEQ}'.",
            file=sys.stderr,
        )
        sys.exit(1)

    h.write(f"inline const char {symbol}[] = R\"{DELIM}(\n")
    h.write(text)
    h.write(f"){DELIM}\";\n")


def emit_binary(h, symbol, path):
    data = path.read_bytes()

    h.write(f"inline const char {symbol}[] = {{\n")

    line_bytes = 0
    for b in data:
        if line_bytes == 0:
            h.write("    ")
        h.write(f"{b}, ")
        line_bytes += 1
        if line_bytes >= 12:
            h.write("\n")
            line_bytes = 0

    if line_bytes == 0:
        h.write("    ")
    h.write("0\n};\n")  # explicit null terminator


def main():
    output_h, readable, pairs = parse_args()

    with open(output_h, "w", encoding="utf-8") as h:
        h.write("// Generated by embed_files.py. Do not edit.\n")
        h.write("#pragma once\n")

        for symbol, path in pairs:
            if readable:
                emit_readable(h, symbol, path)
            else:
                emit_binary(h, symbol, path)


if __name__ == "__main__":
    main()
